### ISSUE TITLE
Unable to install config-resolver >=4.3.6, <5.0

### ISSUE THREAD

**Issue by flazzarini** [exhuma/config_resolver#60]
The `version.txt` is missing in the `MANIFEST.in` and so the version file is not packaged. When trying to install this particular version I get the following error.

```
Collecting config-resolver<6.0
  Downloading config_resolver-4.3.6.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/users/frank/workspace/platformer/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wha05sey/config-resolver/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wha05sey/config-resolver/
setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-wha05sey/config-resolver/pi
p-egg-info
         cwd: /tmp/pip-install-wha05sey/config-resolver/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wha05sey/config-resolver/setup.py", line 10, in <module>
        VERSION = open("config_resolver/version.txt").read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: 'config_resolver/version.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by exhuma** [comment]
This has been resolved in `4.3.6.post2` via 473b4a8cfc
